### ISSUE TITLE
Add TLS support

### ISSUE THREAD

**Issue by jrschumacher** [Fesaa/iCalMerger#7]
Config should support optionally adding TLS. If TLS property is empty then TLS should not be enabled. If TLS property exists then validate and enable TLS.

```
tls:
  version: string # default: TLS12
  cert: string # path
  key: string # path
```
